# Generated by Django 5.2.1 on 2025-05-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
