# Generated by Django 5.2.1 on 2025-05-23 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_registro_is_active_registro_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidas',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partidas',
            name='ronda',
            field=models.IntegerField(default=1),
        ),
    ]
